apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-bot
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "patch"] # "patch" is required for rollout restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-bot-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: restart-bot
    namespace: default
roleRef:
  kind: Role
  name: restart-role
  apiGroup: rbac.authorization.k8s.io
