apiVersion: v1
kind: Service
metadata:
  name: hytale-service
spec:
  type: LoadBalancer
  selector:
    app: hytale
  # Both TCP and UDP are required for Hytale
  ports:
    - protocol: TCP
      port: 5520
      targetPort: 5520
      name: game-tcp
    - protocol: UDP
      port: 5520
      targetPort: 5520
      name: game-udp
    - protocol: TCP
      port: 7003
      targetPort: 7003
      name: prometheus
