apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fivemanage-ingress
  namespace: platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - platform.sone1.no
        - cdn.sone1.no
      secretName: fivemanage-tls
  rules:
    - host: platform.sone1.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fivemanage-lite
                port:
                  number: 80
    - host: cdn.sone1.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
